### ISSUE TITLE
ValueError in Phonon.ApplySumRule()

### ISSUE THREAD

**Issue by vasalx** [SSCHAcode/CellConstructor#35]
Hello CC Developers! Thanks for the great module!

Trying to use the Phonon.Phonon.ApplySumRule() method, I've got the following:

```python
~/opt/miniconda3/envs/sscha/lib/python3.9/site-packages/cellconstructor/Phonons.py in ApplySumRule(self, kind)
   2651 
   2652         # Apply the sum rule on the effective charge
-> 2653         if self.effective_charges != None:
   2654             total_charge = np.sum(self.effective_charges, axis = 0)
   2655 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Effective charges are present in dyn1:

```
     Effective Charges U-E: Z_{s,alpha}{beta}

     atom #    1
      0.462730210279E+02      0.623610318939E-08     -0.316851786928E-30
      0.623609830165E-08      0.462730210275E+02      0.149663389035E-17
     -0.829518700298E-17     -0.478922845063E-17     -0.135643769363E+01
     atom #    2
     -0.236363323590E+02     -0.484650364285E-08      0.106178393638E-14
     -0.484656684587E-08     -0.236363323587E+02      0.306510620763E-14
      0.207379675075E-17      0.119730711266E-17      0.704022189497E+00
     atom #    3
     -0.236363323590E+02     -0.484653561728E-08      0.212356787276E-14
     -0.484645851243E-08     -0.236363323587E+02      0.735625489823E-14
      0.265840019914E-31      0.239461422456E-17      0.704022189497E+00
```

Please let me know if you need more information.

Edit: I've got several large imaginary frequencies (most probably artificial), if this is relevant.

BR,
Oleksandr

**Comment by mesonepigreco** [comment]
Hi, thanks for spotting this bug. 
Usually, I apply the sum rule within the Symmetrize method (which also enforces space group symmetry on the dynamical matrix, so maybe is not what you are looking for).
If you do 
Phonon.Phonon.Symmetrize()
It should automatically applied the sum rule to both the dynamical matrix and the effective charges.

However, I just submitted a fix for the bug you spotted, so if you update the CellConstructor module (from the master repository), you should be able to run also ApplySumRule()
Let us know if it works.

Bests,
Lorenzo

**Comment by vasalx** [comment]
Lorenzo, thanks for getting back so quickly!

I am working with `pip` version.  Don't I need to wait for some time?

Phonon.Phonon.Symmetrize() does the job for now.

Oleksandr

**Comment by mesonepigreco** [comment]
The pip version will take some time to update as we collect multiple bugfixes together before releasing a new version on pip.

In the case you need this master version, once you installed the pip (and you have all the dependencies satisfied), this package can be installed simply with python setup.py install.

**Comment by mesonepigreco** [comment]
I close the issue as it should be solved.
Bests,
Lorenzo
