### ISSUE TITLE
Making the "get_static_correction_along_path" run in parallel

### ISSUE THREAD

**Issue by diegomartinez2** [SSCHAcode/CellConstructor#44]
I'm doing the parallelization of the calculation of the spectral functions. Starting from the static correction.

**Comment by mesonepigreco** [comment]
#45

**Comment by diegomartinez2** [comment]
Not exactly Amdahl's law, but in the same line. For my computer the speed increases asymptotically until the 7th. or 8th. core:
![imagen](https://user-images.githubusercontent.com/101260978/168752719-3ae338f2-442a-44bf-a8f0-d9d1f977e405.png)

Also I have ready the "get_diag_dynamic_correction_along_path_multiprocessing" function with multiprocessing.

**Comment by mesonepigreco** [comment]
Very good, the scaling seems fine as 8 Proc is close to 1/8th of 1 processor, so it is an efficient implementation :) 
Can you add a test in the testsuite when you compare the results of 1 proc and 2 processors (using a very simple and fast calculation of few seconds)? In this way if we screw out something in future, the code will automatically complain. 
You can see the example inside the tests directory, let me know if you need help

**Comment by diegomartinez2** [comment]
For the "get_diag_dynamic_correction_along_path_multiprocessing" function, due to the multi-process calculation the output may not be ordered, so to get the figures you have to sort the data:
       fig, ax1 = plt.subplots(1,1)
        data = np.loadtxt('nomm_spectral_func2_multiprocessing_1.00.dat')
        X = data[:,0]
        Y = data[:,1]
        Z = data[:,2]
        z = [Z[i] for i in np.lexsort((Y,X))]   # <= Here is the sorting part
        data1 = np.resize(z,(int(len(X)/1450),1450))
        cax = ax1.imshow(data1.transpose(), cmap=cm.coolwarm, origin='lower')
        ax1.set_ylabel(r'Frequency (cm$^{-1}$)', fontsize=12)
        plt.xticks(ticks=[0,499,999], labels=['X','G','X'])
        plt.yticks(ticks=[0,200,400,600,800,1000], labels=['0','20','40','60','80','100'])
        cbar = fig.colorbar(cax)
        plt.savefig('spectral_path2_imshow.pdf', bbox_inches='tight')
        plt.savefig('nomm_spectral_func2_multiprocessing_imshow_1.00.png')
        plt.show()
![imagen](https://user-images.githubusercontent.com/101260978/169257233-906aa5df-ceeb-4d62-9d66-007afc072e3e.png)

**Comment by mesonepigreco** [comment]
Ok, that's not the expected behavior I think, can you implement the ordering directly inside the function so that the file is saved already in the correct order and the user must not care about it?

**Comment by mesonepigreco** [comment]
I see why it is difficult: the file is written when you are doing the calculation.
This is really an ugly behaviour (as in any case you have to load it).
It would be much better if the code directly returns the data (ordered) and the saving is done only at the end of the method, after reshuffling correctly the data.

This way we avoid simultaneous access to I/O which could become easily a bottleneck with many processors

**Comment by mesonepigreco** [comment]
One suggestion would be to generate the file as a temporary file, then at the end of the subroutine, read the file and reorder the points and save into the final file.

**Comment by mesonepigreco** [comment]
Now should be fixed and working!
