### ISSUE TITLE
Compilation issues in Conda environments (Fortran compiler)

### ISSUE THREAD

**Issue by max-veit** [SSCHAcode/CellConstructor#54]
Hello,

I have had some issues with the standard compilation (`python setup.py install`) in a new Conda environment with some other necessary packages freshly installed (numpy, scipy, matplotlib, jupyter, ASE, and the direct dependencies setuptools and spglib). The environment uses the system Python version 3.10.4 and this is a Linux 64-bit machine.

I have installed the Conda GCC compiler (`conda install gxx_linux-64`) as suggested in the README, following earlier compilation errors, but it seems also the Conda GFortran compiler is needed -- otherwise, I get the error at runtime:
```
Traceback (most recent call last):
  File "/local/scratch/mveit/miniconda3/envs/atomic/bin/cellconstructor_test.py", line 19, in <module>
    import cellconstructor.Phonons
  File "/local/scratch/mveit/miniconda3/envs/atomic/lib/python3.10/site-packages/cellconstructor/Phonons.py", line 20, in <module>
    import cellconstructor.ForceTensor as ForceTensor
  File "/local/scratch/mveit/miniconda3/envs/atomic/lib/python3.10/site-packages/cellconstructor/ForceTensor.py", line 21, in <module>
    import secondorder
ImportError: /local/scratch/mveit/miniconda3/envs/atomic/lib/python3.10/site-packages/secondorder.cpython-310-x86_64-linux-gnu.so: undefined symbol: _gfortran_os_error_at
```
which I suspect is because it's trying to compile using the system `gfortran` but linking to the Conda `libgfortran.so.4` for some reason; the system `libgfortran.so.5` does have the offending symbol. I haven't yet found a way to make `setup.py` build the module so it links to the system library instead.

The issue was solved in this case by installing the Conda GFortran compiler (LAPack and BLAS are also needed): `conda install -c conda-forge gfortran_linux-64 liblapack libblas`. Perhaps it would be helpful to mention this in the install documentation.

Thank you,
Max

**Comment by mesonepigreco** [comment]
Hi Max,
You can try to enforce the compiler and linker using
FC=gfortran LD_SHARED=gfortran python setup.py install

Replacing gfortran with the correct path to the compiler. Thanks for spotting this flaw in the documentations. We will fix it.

**Comment by mesonepigreco** [comment]
The compilation within conda is now fully supported as explained in the installation guide.
