### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by kw600** [SSCHAcode/CellConstructor#77]
In Spectral.py, the function get_static_correction_interpolated() has a bug on these two lines:
    for iq in range(len(q_tot)):
        new_dyn.dynmats.append(dynq[iq, :, :])
The new_dyn.dynmats alread has an initial zero dynamical matrix. If the new dynq is added into new_dyn.dynmats, the gamma point dynamical is always the zero dynamical matrix. Therefore, for iq=0, instead of using the append, one should use new_dyn.dynmats[iq] = dynq[iq, :, :].

**Comment by mesonepigreco** [comment]
Thanks a lot for the bug report!

@rafbianco @diegomartinez2 , I think this could be related to the bug observed also by @marcocherubini ? 
Do some of you have time to look if this was the issue?

**Comment by diegomartinez2** [comment]
What bug by @marcocherubini? I'm a bit lost here.

**Comment by mesonepigreco** [comment]
Sorry, @marcocherubini spotted a bug few years ago which we never understood occurring when interpolating the static respose function on a path in some systems.
Anyway, this should be fixed with High priority before the release of 1.4

**Comment by diegomartinez2** [comment]
Do you remember an example of one of those systems to check the fix?

**Comment by mesonepigreco** [comment]
Still to be added a test in the testsuite that check for the correct functioning of get_static_correction_interpolated
